apiVersion: v1
kind: Service
metadata:
  name: golang-jenkin
  labels:
    app: golang-jenkin
spec:
  selector:
    app: golang-jenkin
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP